from typing import Protocol, runtime_checkable, Self, Sequence, Hashable

class Sentence(Protocol):
    def __iter__(self) -> Iterator[Hashable]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Hashable: ...

    @classmethod
    def empty(cls): ...
    @classmethod
    def lift(cls, symbol) -> Sentence: ...
    
    def combine(self, other: Self) -> Self: ...
    def clone(self) -> Self: ...
